name: Execute Command
description: Execute an arbitrary command and capture its output
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: terminal
  color: blue

# Define your inputs here.
inputs:
  command:
    description: The command to execute
    required: true
  success_exit_codes:
    description: >
      Exit codes that should be treated as success. Can be individual codes
      (e.g., "0,1,2") or ranges (e.g., "0-2,5,10-15"). Default is "0".
    required: false
    default: '0'

# Define your outputs here.
outputs:
  stdout:
    description: The standard output of the command
  stderr:
    description: The standard error of the command
  exit_code:
    description: The exit code of the command

runs:
  using: node24
  main: dist/index.js
